### ISSUE TITLE
`named` queries denied

### ISSUE THREAD

**Issue by smattingly** [dewv/ops#1]
Daily log check finds named queries denied from various outside hosts. Should investigate this. Example below. Others are pretty much the same except for the host.
```
Mar 13 08:20:27 s17925818 named[30442]: client 145.220.24.215#51402 (anqojxlm.or.mkorczynski.com): query (cache
) 'anqojxlm.or.mkorczynski.com/A/IN' denied
```

**Comment by Emreyildirim1284** [comment]
As far as I know that this is not a attack, this means that our DNS needs to be reconfigured. Currently I am looking into how to do that.

**Comment by Emreyildirim1284** [comment]
🍅 🍅

**Comment by smattingly** [comment]
> 
> 
> As far as I know that this is not a attack, this means that our DNS needs to be reconfigured. Currently I am looking into how to do that.

Ok-- if you find good information sources, link them here.

**Comment by Emreyildirim1284** [comment]
🍅

**Comment by Emreyildirim1284** [comment]
https://serverfault.com/questions/429528/view-external-query-cache-denied-on-bind9-named

The first answer looks useful. Please take a look at it and let me know what do you think.

**Comment by Emreyildirim1284** [comment]
🍅

**Comment by smattingly** [comment]
@Emreyildirim1284 I don't think the answer looks useful. It is referring to localhost and private IP addresses, but our message is referring to external public addresses. The person posting the answer did not respond to the request for why they think that answer would fix things. 

I'm not sure, but I wonder if we lost our DNS configuration when we recently set some automatic upgrades running. I remember working with some of [these instructions](https://help.ubuntu.com/14.04/serverguide/dns-configuration.html), but when I look at `/etc/bind` now, almost all config files are timestamped in 2014 and look like defaults.

Maybe this task should be redefined to be: use that Ubuntu guide to figure out the DNS configuration that we want to use, and put it in place. (I don't remember which role(s) we need our DNS to do.) If that does not fix the log messages we're seeing, we can go from there.

**Comment by Emreyildirim1284** [comment]
Hey Mr.Mattingly
We usually get one of these per day but it looks like we got 3 today for some reason.I don't think it is anything really serious but it would be the best if we can find a solution for this as soon as possible. I need to ask you couple questions about the DNS configuration stuff. I read about the instructions but I need some help. By the way I am pasting what we got today below

Apr  9 17:03:45 s17925818 named[30442]: client 116.62.217.151#42609 (aids.gov): query (cache) 'aids.gov/ANY/IN' denied
Apr  9 17:03:47 s17925818 named[30442]: client 116.62.217.151#46822 (aids.gov): query (cache) 'aids.gov/ANY/IN' denied
Apr  9 17:03:48 s17925818 named[30442]: client 116.62.217.151#37983 (aids.gov): query (cache) 'aids.gov/ANY/IN' denied

**Comment by Emreyildirim1284** [comment]
This is not even a random domain. It ends with "gov"

**Comment by Emreyildirim1284** [comment]
🍅

**Comment by Emreyildirim1284** [comment]
Done
