### ISSUE TITLE
Issue: "error: PAM: Authentication failure for illegal user help from ( an IP)"

### ISSUE THREAD

**Issue by Sprite411** [dewv/ops#120]
This was an anomaly I noticed pop up a couple times between 8:43 and 8:49 on 4/29/2020. Found on a daily server log check.

**Comment by smattingly** [comment]
I assume this is for ssh services. It might be worth changing the firewall to restrict IP addresses for ssh (and other services?)

**Comment by smattingly** [comment]
No recurrence.
