### ISSUE TITLE
"error: Received disconnect from (an IP) port (...): com.jcraft.jsch.JSchException: Auth cancel [preauth]"

### ISSUE THREAD

**Issue by Sprite411** [dewv/ops#121]
Another thing that popped up several times on a daily check that was weird. It showed up at 18:01:54, 18:16:01, 18:50:00, 19:08:21, 19:26:51, 19:25:27, 20:04:04, 20:22:04, 20:42:00, 21:01:00.

**Comment by smattingly** [comment]
No recurrence.
