### ISSUE TITLE
Research fstrim error

### ISSUE THREAD

**Issue by smattingly** [dewv/ops#67]
`systemctl status fstrim` shows errors: "Discard unused blocks" failed to start

**Comment by ShakenMusic122** [comment]
These help describe other fstrim problems people have faced that might help us face our problem:
-https://bugs.archlinux.org/task/62288
-https://www.linuxquestions.org/questions/linux-hardware-18/how-often-should-i-use-use-fstrim-4175630358/

**Comment by smattingly** [comment]
The links above plus my own searches say: some SSDs do not support the fstrim command. It appears that ours is one. Don't know why hosting vendor set it up that way. 

I suspect that we can/should disable the scheduled fstrim job. @fantasticfink Can you please comment with the following info from the test VM:
- output of `sudo fstrim -a -v`
- output of `sudo cat /etc/fstab`
- specifics of drive type from VM setup

**Comment by finkrobertb** [comment]
`sudo fstrim -a -v` output: 
None

`sudo cat /etc/fstab` output: 
UUID=08ff06f7-a5e5-4ee4-b933-c0a4cff51623 / ext4 defaults 0 0 
/swap.img        none      swap      sw      0      0

`cat /sys/block/sda/queue/rotational` output: 1
(This command reports back 1 for HDD, 0 for SSD.  Apparently it thinks I'm using a HDD, but there is a SSD in my laptop) (https://www.milesweb.com/hosting-faqs/how-to-check-if-disk-is-ssd-or-normal-hdd/)

**Comment by smattingly** [comment]
Thanks @fantasticfink 

The first command outputs an error on the production machine.

Remember that the VM does not use your laptop's drives *from its perspective*. It uses the virtual drives defined for it by VirtualBox. So your virtual drive for this VM is HDD. 

So, the VM is reproducing production server *software*, but not hardware. That doesn't matter until we try to troubleshoot something like this issue. Not sure how closely we could make the VM match the production "hardware" (it's actually virtual, too). Might not be worth investing much effort because PaaS hosting and/or Ansible etc. might make current VM obsolete.

**Comment by smattingly** [comment]
@ShakenMusic122 On the production server, I have just run

```bash
 systemctl stop fstrim.timer
 systemctl disable fstrim.timer
```
I believe this should disable the scheduled fstrim job and put an end to errors in the log.

To verify this, please log on to the production server on Wed 8 Apr and run `journalctl --since 2020-03-31 | grep fstrim`. There should be no output. If there is none, close this Issue. If there is output, post it here and @ me.

**Comment by ShakenMusic122** [comment]
I have just run your command. Sorry for the lateness. There was no output.
