### ISSUE TITLE
Research log message "ignoring max retries"

### ISSUE THREAD

**Issue by smattingly** [dewv/ops#70]
Logs contain messages like `PAM service(sshd) ignoring max retries; 5 > 3`. Research to see if this is a security concern that can/should be addressed.

**Comment by finkrobertb** [comment]
PAM (Pluggable Authentication Modules) is a suite of shared libraries used to authenticate a user to applications or services.  Apparently the PAM and ssdh are not configured to have the same number of user password retries.  Here is a link that describes the steps to make them both 3:

https://superuser.com/questions/1010607/pam-service-sshd-ignoring-max-retries-6-3

**Comment by finkrobertb** [comment]
Attempted on test server with the following commands:

`sudo nano /etc/ssh/sshd_config` (open sshd_config to edit)
Type `MaxAuthTries 3` somewhere in the file
Press `Ctrl + O` to save
Press `Ctrl + X` to exit
Possibly reboot server

Not able to test, as the server is not fully functional

**Comment by smattingly** [comment]
@fantasticfink Can you explain what the status of the local VM server is? What needs to get working to make this testable?

**Comment by finkrobertb** [comment]
We still need to fix the nginx issue we spoke about earlier.  We need to be able to configure the server to redirect to localhost instead of the actual server.  I haven't done much research since last time we spoke.

**Comment by smattingly** [comment]
@fantasticfink Unless, I'm forgetting, the only issue was to be sure that you used http***S*** to avoid being redirected to the production server.

I think that risk might be eliminated by changing the `nginx.conf` line that says
```
return 301 https://www.dewv.net$uri;
```
to read
```
return 301 https://$http_host$uri;
```

**Comment by finkrobertb** [comment]
![Screenshot (112)](https://user-images.githubusercontent.com/42548932/77923754-dc879c80-7270-11ea-9a77-5062c9b9091a.png)

The PAM error is not currently displaying on the test server after the changes were made and the `nginx.conf` was edited to redirect to the host and not the production server.

**Comment by smattingly** [comment]
@fantasticfink I think it makes sense to mark this closed. I just created and assigned you to #109 , which covers the research you have already done plus trying out one or more of those tools.
