### ISSUE TITLE
Research 'Unknown SG version '/block/sda'

### ISSUE THREAD

**Issue by Sprite411** [dewv/ops#74]
On Jan 29 at 22:00:04 and 22:00:24 Unknown SG version '/block/sda' pops up in red.

**Comment by smattingly** [comment]
@Spritte77 A reminder: you were assigned to see what Internet research on this might turn up. Please see what you can find and post potentially relevant info as comments on this Issue.

**Comment by smattingly** [comment]
No recurrence.
