### ISSUE TITLE
Log check "failed to parse timestamp 2-13-2020"

### ISSUE THREAD

**Issue by Weintraubm** [dewv/ops#86]
- [ ] Replace the default title with a brief, clear summary of the problem.
- [ ] Click `Submit new issue` to generate this Issue's number (needed below), then continue editing this Issue as follows.

- [ ] If the problem prevents check-in and/or check-out, or causes other *major* disruption to the NLC app, apply the `EMERGENCY` label to this Issue.

If this issue was reported to `help@dewv.net` by customer or user:
- [ ] Apply the `Customer initiated` label to this Issue.
- [ ] Use the `help@dewv.net` account to reply to the email using the "Reply to customer's report of operations problem" template.

Else (this problem was not reported by customer)
- [ ] Use the `help@dewv.net` account to mail customers using the "Notify customer we detected operations problem" template.

**Comment by smattingly** [comment]
@Weintraubm Was the error from the `daily.sh` script? It expects the date in `YYYY-MM-DD` format.

**Comment by Weintraubm** [comment]
much user error, chalk that one up to my bad. I in fact wrote the date backwards of what it wanted. I'll be more careful in the future.
